name: minithesis_dart
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
#dependencies:

dev_dependencies:
  lints: ^6.0.0
  parameterized_test: ^2.0.1
  test: ^1.24.0
  test_process: ^2.1.1
dependencies:
  fixnum: ^1.1.1
  collection: ^1.19.1
  path: ^1.9.1
  crypto: ^3.0.6
  stack: ^0.2.2
  checks: ^0.3.0
